name: Build SWU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ❗ NO GHCR LOGIN
      # ❗ NO REGISTRY CACHE
      # ❗ Fork-safe build

      - name: Build and export SWU
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          build-args: |
            version=${{ github.sha }}
          outputs: type=local,dest=./build/dist

      - name: Upload artifact for K2P, K3
        uses: actions/upload-artifact@v4
        with:
          name: update-k2p-k3
          compression-level: 0
          path: |
            build/dist/*-k2p-k3.swu
            build/dist/*-k2p-k3.zip

      - name: Upload artifact for KS1
        uses: actions/upload-artifact@v4
        with:
          name: update-ks1
          compression-level: 0
          path: |
            build/dist/*-ks1.swu
            build/dist/*-ks1.zip

      - name: Upload artifact for KS1M
        uses: actions/upload-artifact@v4
        with:
          name: update-ks1m
          compression-level: 0
          path: |
            build/dist/*-ks1m.swu
            build/dist/*-ks1m.zip

      - name: Upload artifact for K3M
        uses: actions/upload-artifact@v4
        with:
          name: update-k3m
          compression-level: 0
          path: |
            build/dist/*-k3m.swu
            build/dist/*-k3m.zip
